version: '3'

services:
  client-web:
    image: combo-client-web:latest
    build: ./client-web
    volumes:
      - ./client-web/public/:/var/www/html/
      - ./client-web/config/nginx.local.conf:/etc/nginx/conf.d/nginx.env.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - server-api
    networks:
      - client-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  server-api:
    image: combo-server-api:latest
    build: ./server-api
    command: [ "npm", "run", "start-local" ]
    volumes:
      - ./server-api:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=local
    networks:
      client-network:
      server-network:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  client-network:
  server-network:
