version: '3'

services:
  client-web:
    image: combo-client-web:latest
    build: ./client-web
    volumes:
      - ./client-web/public/:/var/www/html/
      - ./client-web/config/nginx.local.conf:/etc/nginx/conf.d/nginx.env.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - server-api
    networks:
      - client-network
    restart: unless-stopped

  server-api:
    image: combo-server-api:latest
    build: ./server-api
    command: [ "npm", "run", "start-local" ]
    volumes:
      - ./server-api:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - database
    environment:
      - NODE_ENV=local
      - DATABASE_URL=postgresql://combo_app_user@database/combo_local
    networks:
      client-network:
      server-network:
    restart: unless-stopped

  database:
    image: postgres:9.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: combo_app_user
      POSTGRES_DB: combo_local
    networks:
      server-network:
    restart: unless-stopped

networks:
  client-network:
  server-network:
